### ISSUE TITLE
Issue with Raspberry Pi Zero 2 W

### ISSUE THREAD

**Issue by mraess** [ryanwa18/spotipi#3]
I have installed spotipi on a Raspberry Pi 3B+ and it works great. 

Today I tried running it on a new Raspberry Pi Zero 2W to no avail. I have blacklisted the `blacklist snd_bcm2835` audio driver since that seems to be necessary. 

After the install process, I went to the flask-web app to see if the application was running because I could not see any matrix output. When I try to change the brightness, I get a server error which seems weird.

So two issues:

1) No output on matrix with same install and settings (client_id, secret, .cache-file, etc) as on the Pi 3B+.
2) The web app throws error messages when trying to change the brightness, which seems to suggest an underlying issue maybe.

Any advice on how to proceed from here?

**Comment by flasher69** [comment]
I've checked and I have also the same problem with Rpi zero 2 W. Interessting is that I've swaped my card from Rpi zero W in Rpi zero 2 W and it seems to work just fine! So I think something doesn't install right when you are installing the spotipi on Rpi zero 2 W

**Comment by flasher69** [comment]
i'm not sure but maybe it's a python problem on Bullseye. I'm trying the Pi os legasy now and see if it works better

**Comment by ryanwa18** [comment]
I didn't even know that there was a new Raspberry Pi zero 2. I will have to buy one and see if I can update the code on another branch to support this :)

**Comment by flasher69** [comment]
it doesn't seem to only be a RPI zero 2 W issue. I'm trying to do the same steps on a RPi 3B + and RPi zero W and nothing works correctly. I'm starting to believe that it has something to do with Raspian Bullseye or missing libraries, etc. I'll try the whole prossess again later.

**Comment by flasher69** [comment]
After playing around for hours I think the issue is not the Rpi zero 2 w but Bullseye. I've installed Raspberry OS Buster and installed Spotipi and it works. So I think that the problem is that there are some incompatibility und missing parts.

**Comment by cjc-dev** [comment]
Can confirm that I experienced no output on the RGB matrix when using Bullseye but things work as expected after flashing Buster onto the SD card which I use with the Zero 2 W  connected to a 32 x 32 matrix

**Comment by ryanwa18** [comment]
I appreciate you guys bringing this issue to my attention. I’m also glad it seems like some of you guys have had success in setting it up for yourself.

Do you have any feedback on the install process on things I can improve?

**Comment by flasher69** [comment]
Dear Ryan,

I had big issues at the beginning with creating the .cache file on my Macbook Pro (OS 10.15.7). Somehow a lot of dependencies and python didn't really install that well. I was able to get it to run after creating virtual environment like discription here:
https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/

I haven't tried this on my windows since you did your video on a mac terminal. So I wanted to follow your instructions as close to yours as possible.

I  wish there was a way to change the resolution or more chains of panels in your web interface. I had success with four panels (2 x 2 panels = 128 x 128 LED) after editing the rgb_options.ini but it was a bit annoying to restart rpi each time after editing. Is there a way to stop and restart spotipi without restarting the Rpi? I was playing with the idea of running animations and gifs on the same rpi and panels, in case I'm not using Spotify. Any suggestions?

Beside all this thank you so much for this script. I really love it. In the past I did follow different scripts for Esp32 and Rpi but I think your solution was way better than the others.

cheers

**Comment by mraess** [comment]
@flasher69 thanks for the detailed comments! I'll try it on Buster as soon as I get a chance and will report back.

@ryanwa18 the Rpi Zero 2 W is awesome. It boots so much faster than the first version - same form  factor at $15!!

**Comment by kylejohnsonkj** [comment]
> I was able to get it to run after creating virtual environment like discription here: https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/

@flasher69 I was failing to create the token too (only had pip3), virtual environment worked for me 👍

**Comment by ryanwa18** [comment]
This should definitely be added as a feature in the install. It should be installed using a virtual environment to be compatible across different operating systems. I can add that to my list of improvements.

**Comment by flasher69** [comment]
![2022-01-07 18 52 52-1](https://user-images.githubusercontent.com/22278347/148679493-62775f15-69db-4804-81c9-2f6af549a51e.jpg)

I thought I send you a picture of my 128 x 128 matrix (4 Hub75) and RPi4 in a frame. I really like how it turned. It also works with Rpi zero 2 W but there was some flickering. That's why I've decided to go with a Rpi 4.

**Comment by ryanwa18** [comment]
This looks amazing. I absolutely love the frame you made for it. This makes me want to get a 3d printer now. Great work!

**Comment by mraess** [comment]
@flasher69, this looks amazing! Do you have the code snippet you had to change for the 128x128 resolution?

**Comment by flasher69** [comment]
> @flasher69, this looks amazing! Do you have the code snippet you had to change for the 128x128 resolution?

I did post my settings here:

https://github.com/ryanwa18/spotipi/issues/5#issuecomment-998201606

**Comment by flasher69** [comment]
> This looks amazing. I absolutely love the frame you made for it. This makes me want to get a 3d printer now. Great work!

Thanx Ryan. The frame itself is  a wooden frame, which I bought online here in germany. I had to 3d print some parts to connect the panels together. Here some more detail photos. 
Btw, I'm using Anycubic Vyper for my 3D-prints.

![Frame_detail1](https://user-images.githubusercontent.com/22278347/148698593-72e31b70-35ba-45d8-9aad-03d56cb7b850.jpg)
![Frame_detail2](https://user-images.githubusercontent.com/22278347/148698603-f71eabfe-ae34-49ab-9148-cfcd99fb5f73.jpg)
![Frame_detail3](https://user-images.githubusercontent.com/22278347/148698605-46bd616d-9fe5-4d46-9c96-967c087d3cac.jpg)
